# Generated by Django 3.1.7 on 2021-03-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='Значение проблемы в диаграмме')),
                ('problem', models.CharField(max_length=128, verbose_name='Проблема')),
            ],
        ),
    ]
