# Generated by Django 3.1.7 on 2021-03-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0002_region'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagram',
            options={'verbose_name': 'Диаграмма', 'verbose_name_plural': 'Диаграммы'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Регион', 'verbose_name_plural': 'Регионы'},
        ),
        migrations.RemoveField(
            model_name='region',
            name='diagram',
        ),
        migrations.AddField(
            model_name='region',
            name='diagram',
            field=models.ManyToManyField(related_name='diagrams', to='diagram.Diagram'),
        ),
    ]
