# Generated by Django 3.1.7 on 2021-03-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0003_auto_20210325_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Навание ведомства')),
            ],
            options={
                'verbose_name': 'Ведомство',
                'verbose_name_plural': 'Ведомства',
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Проблема')),
            ],
            options={
                'verbose_name': 'Проблемма',
                'verbose_name_plural': 'Проблеммы',
            },
        ),
        migrations.CreateModel(
            name='ProblemCluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Категория проблем')),
                ('ministries', models.ManyToManyField(related_name='mynistries', to='diagram.Ministry', verbose_name='Министерства')),
            ],
            options={
                'verbose_name': 'Категория проблем',
                'verbose_name_plural': 'Категории проблем',
            },
        ),
        migrations.RemoveField(
            model_name='diagram',
            name='problem',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.AddField(
            model_name='ministry',
            name='problems',
            field=models.ManyToManyField(related_name='problemas', to='diagram.Problem'),
        ),
        migrations.AddField(
            model_name='diagram',
            name='problemcluster',
            field=models.ManyToManyField(related_name='problemsCluster', to='diagram.ProblemCluster', verbose_name='Категории проблем'),
        ),
    ]
