# Generated by Django 3.1.7 on 2021-03-25 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0004_auto_20210326_0019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'verbose_name': 'Проблема', 'verbose_name_plural': 'Проблемы'},
        ),
    ]
