# Generated by Django 3.1.7 on 2021-03-25 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0005_auto_20210326_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ministry',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название ведомства'),
        ),
        migrations.AlterField(
            model_name='problemcluster',
            name='ministries',
            field=models.ManyToManyField(related_name='mynistries', to='diagram.Ministry', verbose_name='Ведомства'),
        ),
    ]
