# Generated by Django 3.1.7 on 2021-03-25 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0006_auto_20210326_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagram',
            name='problemcluster',
        ),
        migrations.AddField(
            model_name='diagram',
            name='problemcluster',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='diagram.problemcluster', verbose_name='Категории проблем'),
            preserve_default=False,
        ),
    ]
