# Generated by Django 3.1.7 on 2021-03-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0007_auto_20210326_0111'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemDetailed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
