# Generated by Django 3.1.7 on 2021-03-26 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0008_problemdetailed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProblemDetailed',
        ),
    ]
