# Generated by Django 3.1.7 on 2021-03-28 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0009_delete_problemdetailed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ministry',
            old_name='name',
            new_name='min_name',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='name',
            new_name='prob_name',
        ),
        migrations.RenameField(
            model_name='problemcluster',
            old_name='name',
            new_name='probClus_name',
        ),
        migrations.RemoveField(
            model_name='diagram',
            name='problemcluster',
        ),
        migrations.RemoveField(
            model_name='diagram',
            name='value',
        ),
        migrations.CreateModel(
            name='DiagramElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='Значение проблемы в диаграмме')),
                ('problemcluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagram.problemcluster', verbose_name='Категории проблем')),
            ],
            options={
                'verbose_name': 'Столбец диаграммы',
                'verbose_name_plural': 'Столбцы диаграммы',
            },
        ),
        migrations.AddField(
            model_name='diagram',
            name='columns',
            field=models.ManyToManyField(to='diagram.DiagramElement', verbose_name='Диаграмма'),
        ),
    ]
