# Generated by Django 3.1.7 on 2021-03-26 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ministries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Ведомство',
                'verbose_name_plural': 'Ведомства',
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prob_name', models.CharField(max_length=300, verbose_name='Проблема')),
                ('ministries', models.ManyToManyField(to='detail.Ministries', verbose_name='Ведомства')),
            ],
            options={
                'verbose_name': 'Проблема',
                'verbose_name_plural': 'Проблемы',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serv_name', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Госуслуга',
                'verbose_name_plural': 'Госуслуги',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_name', models.CharField(max_length=100, verbose_name='Регион')),
                ('problems', models.ManyToManyField(to='detail.Problem', verbose_name='Проблемы')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.AddField(
            model_name='ministries',
            name='services',
            field=models.ManyToManyField(to='detail.Services', verbose_name='Госуслуги'),
        ),
    ]
